name: polyconstruct-docs
channels:
  - conda-forge
  - defaults
source:
  path: ./source/polyconstruct-sphinx-theme
dependencies:
  # Base depends
  - python
  - pip
  - polyconstruct-sphinx-theme

  # MDAnalysis
  - MDAnalysis

  # Testing
  - pytest
  - pytest-cov
  - pytest-xdist
  - codecov

  - IPython
  - jupyter
  - nbconvert
  - nbformat
  - pytest
  - rdkit
  - py3Dmol
  - numpy
  - mdanalysis
  - click
  - py3Dmol
  - networkx
  - tqdm